Group and Event integration
Catalyze-Software/proxy-v2 pull request #7
Opened 2024-08-19 07:42 UTC by napalmpapalam

2024-08-21 08:46 UTC, napalmpapalam commented on src/proxy/src/calls/generic_calls.rs
> +    let _ = BoostCalls::start_timers_after_upgrade().await;
not sure how to handle result here, do I need trap?

2024-08-21 08:46 UTC, napalmpapalam commented on src/proxy/src/calls/group_calls.rs
>  #[update(guard = "is_not_anonymous")]
why its update call?

2024-08-21 10:00 UTC, rem-code-s requested changes

2024-08-21 10:00 UTC, rem-code-s commented on src/proxy/src/calls/stats_calls.rs
> +        format!("BoostStore: {}", boosteds().size().await?),
`boosteds`? 🤣  `boosts` is probably better

2024-08-21 10:00 UTC, rem-code-s commented on src/proxy/src/logic/report_logic.rs
> +        let is_group_joined = group
There is also a `is_member` method

2024-08-21 10:00 UTC, rem-code-s commented on src/proxy/src/calls/generic_calls.rs
> +    let _ = BoostCalls::start_timers_after_upgrade().await;
good question, i don't think its wise to trap on this on the post upgrade based the the importance of this timer, so i suggest leaving it as is

2024-08-21 10:07 UTC, napalmpapalam commented on src/proxy/src/logic/report_logic.rs
> +        let is_group_joined = group
Yeah, coz I added some after dat change :D

2024-08-21 10:30 UTC, rem-code-s commented on src/proxy/src/calls/group_calls.rs
>  #[update(guard = "is_not_anonymous")]
Seems like a mistake, the description says it should be a query

2024-08-21 10:33 UTC, napalmpapalam commented on src/proxy/src/calls/group_calls.rs
>  #[update(guard = "is_not_anonymous")]
fixed

2024-08-22 07:55 UTC, rem-code-s approved these changes

2024-08-22 08:01 UTC, merged